name: Basic Continuous Integration Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      # Fix PyQt6 installation issues on Windows
      - name: Reinstall PyQt6 (Windows)
        if: runner.os == 'Windows'
        run: |
          pip uninstall -y PyQt6 PyQt6-Qt6 PyQt6-sip
          pip install --no-cache-dir PyQt6==6.5.0

      # Ensure Qt DLLs are in PATH
      - name: Fix PyQt6 DLL Path (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "C:\hostedtoolcache\windows\Python\3.9.13\x64\Lib\site-packages\PyQt6\Qt6\bin" >> $GITHUB_PATH
          echo "PATH: $PATH"
          ls "C:\hostedtoolcache\windows\Python\3.9.13\x64\Lib\site-packages\PyQt6\Qt6\bin"

      # Verify PyQt6 before running the app
      - name: Verify PyQt6 Installation
        if: runner.os == 'Windows'
        run: python -c "from PyQt6.QtCore import QCoreApplication; print('PyQt6 is working!')"

      # Install other dependencies
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # Run application
      - name: Run application
        run: python main.py