name: Basic Continuous Integration Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      # Linux-only: install system dependencies
      - name: Install system dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1-mesa libgles2-mesa

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      # Run on Linux using xvfb and offscreen mode
      - name: Run application (Linux with Xvfb)
        if: runner.os == 'Linux'
        run: |
          export QT_QPA_PLATFORM=offscreen
          xvfb-run -a python main.py

      # Run normally on Windows and macOS
      - name: Run application (Windows & macOS)
        if: runner.os != 'Linux'
        run: python main.py

