name: Basic Continuous Integration Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      # Upgrade pip only on non-Windows runners.
      - name: Upgrade pip (Linux & macOS)
        if: runner.os != 'Windows'
        run: python -m pip install --upgrade pip

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      # (Optional) If your app uses a GUI on Linux, you might need xvfb:
      - name: Run application (Linux with Xvfb)
        if: runner.os == 'Linux'
        run: xvfb-run python main.py

      # On Windows and macOS, run the app normally
      - name: Run application (Windows & macOS)
        if: runner.os != 'Linux'
        run: python main.py
