name: Basic Continuous Integration Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      # Ensure PyQt6 DLLs are accessible on Windows
      - name: Fix PyQt6 DLL Path Issue (Windows)
        if: runner.os == 'Windows'
        run: echo "C:\hostedtoolcache\windows\Python\3.9.13\x64\Lib\site-packages\PyQt6\Qt6\bin" >> $GITHUB_PATH

      - name: Install Specific PyQt6 Version
        run: |
          pip install --force-reinstall --no-cache-dir PyQt6==6.5.0
          pip install -r requirements.txt

      # Check if PyQt6 loads properly before running app
      - name: Verify PyQt6 Installation
        run: python -c "from PyQt6.QtCore import QCoreApplication; print('PyQt6 is working!')"

      - name: Run application
        run: python main.py
